### ISSUE TITLE
Competitive programming

### ISSUE THREAD

**Issue by Atharvp18** [SarthakKeshari/CPP-Questions-and-Solutions#95]
### A brief about your proposal - 
Hello, Please assign me this task I will add cpp solutions for questions from the CodeChef platform as a hacktoberfest contribution.
Thank you

**Comment by SarthakKeshari** [comment]
@Atharvp18,
Kindly create an issue and provide a question that you wish to solve.
Since question would be from online platform make sure to take up medium and hard level questions

Strict advice -
Be original in your code. In case of found plagarism in later review even after a successful merge may lead to ban.

**Comment by SarthakKeshari** [comment]
@Atharvp18,
Any other queries or shall I close this issue.

**Comment by Atharvp18** [comment]
Okay, I will make another issue with the question link I will be solving, yeah sure close this issue.

Thank you
