### ISSUE TITLE
CodeChef Problems

### ISSUE THREAD

**Issue by gb07bh** [SarthakKeshari/CPP-Questions-and-Solutions#96]
Hey, I would love to add at least 5 Codechef problem solutions to your repository as an Hacktoberfest 2021 contribution.
If you would want this, please assign me.

**Comment by SarthakKeshari** [comment]
@gb07bh,
Kindly create an issue and provide a question that you wish to solve.
Since question would be from online platform make sure to take up medium and hard level questions

Strict advice -
Be original in your code. In case of found plagarism in later review even after a successful merge may lead to ban.

**Comment by SarthakKeshari** [comment]
@gb07bh,
Any other queries or shall I close this issue.

**Comment by gb07bh** [comment]
You may close the issue. I would create pull requests and surely imply with the given instructions.
